version: '3.5'

services:
  postgres:
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mitidb
      CONTAINER_NAME: mitidb-container

    ports:
      - 5432:5432
